aa: rand-m9-mstd0.5-inc1
batch_size: 128
clip_grad: null
color_jitter: 0.4
cooldown_epochs: 10
cutmix: 1.0
cutmix_minmax: null
decay_epochs: 30
decay_rate: 0.1
device: cuda
drop: 0.0
drop_block: null
drop_path: 0.1
embed_dim: 48
epochs: 300
eval: false
inat_category: name
img_size: 32
mean:
    - 0.4914
    - 0.4822
    - 0.4465
std:
    - 0.2470
    - 0.2435
    - 0.2616
crop_pct: 1.0
scale:
    - 0.8
    - 1.0
local_up_to_layer: 10
locality_strength: 1.0
lr: 0.0005
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
min_lr: 1.0e-05
mixup: 0.8
mixup_mode: batch
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: convit_small
model_ema: false
model_ema_decay: 0.99996
model_ema_force_cpu: false
momentum: 0.9
nb_classes: null
num_workers: 10
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output_dir: ''
patience_epochs: 10
pin_mem: true
pretrained: false
recount: 1
remode: pixel
repeated_aug: true
reprob: 0.25
resplit: false
resume: ''
sampling_ratio: 1.0
save_every: null
sched: cosine
seed: 0
smoothing: 0.1
start_epoch: 0
train_interpolation: bicubic
warmup_epochs: 5
warmup_lr: 1.0e-06
weight_decay: 0.05
world_size: 1
